name: Create App Artifacts
on:
 pull_request:

 push:
   branches:
     - dev-branch

# Cancel active CI runs for a PR before starting another run
concurrency:
 group: ${{ github.workflow}}-${{ github.ref }}
 cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
 FORCE_COLOR: "1"

defaults:
 run:
   shell: bash

jobs:
 ci:
   name: Test and Package
   runs-on: ${{ matrix.runs-on }}

   strategy:
     fail-fast: false
     matrix:
       target: [ "Windows", "macOS", "Ubuntu-24.04", "Fedora-40", "Android"]
       include:
         - target: "Windows"
           output-format: "app"
           runs-on: "windows-latest"

         - target: "macOS"
           output-format: "app"
           runs-on: "macos-latest"

         - target: "Ubuntu-24.04"
           platform: "Linux"
           output-format: "system"
           runs-on: "ubuntu-latest"
           pre-command: "sudo apt-get -y install socat libcairo2-dev libgirepository1.0-dev --fix-missing"
           briefcase-run-prefix: "xvfb-run"
           briefcase-args: "--target ubuntu:24.04"

         - target: "Fedora-40"
           platform: "Linux"
           output-format: "system"
           runs-on: "ubuntu-latest"
           pre-command: "sudo apt-get -y install socat libcairo2-dev libgirepository1.0-dev --fix-missing"
           briefcase-run-prefix: "xvfb-run"
           briefcase-args: "--target fedora:40"

         - target: "Android"
           output-format: "Gradle"
           runs-on: "ubuntu-latest"
           pre-command: |
             # Enable KVM permissions for the emulator
             echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
               | sudo tee /etc/udev/rules.d/99-kvm4all.rules
             sudo udevadm control --reload-rules
             sudo udevadm trigger --name-match=kvm
           briefcase-run-args: >-
             --device '{"avd":"beePhone"}'
             --shutdown-on-exit
             --Xemulator=-no-window
             --Xemulator=-no-snapshot
             --Xemulator=-no-audio
             --Xemulator=-no-boot-anim

   steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Install Briefcase
       run: |
         python3 -m pip install -U pip setuptools wheel --break-system-packages
         python3 -m pip install briefcase --break-system-packages

     - name: Setup Environment
       working-directory: ./pypass
       run: |
         # Use GitHub's preinstalled JDK 17 for Android builds
         echo JAVA_HOME="${JAVA_HOME_17_X64:-$JAVA_HOME_17_arm64}" | tee -a ${GITHUB_ENV}
         ${{ matrix.pre-command }}

     - name: Update briefcase tools
       working-directory: ./pypass
       run: briefcase upgrade --no-input --log

     - name: Build App
       working-directory: ./pypass
       run: |
         ${{ matrix.briefcase-build-prefix }} \
         briefcase build \
           ${{ matrix.platform || matrix.target }} \
           ${{ matrix.output-format }} \
           --test --no-input --log \
           ${{ matrix.briefcase-args }} \
           ${{ matrix.briefcase-build-args }}

     - name: Test App

       working-directory: ./pypass
       run: |
         ${{ matrix.briefcase-run-prefix }} \
         briefcase run \
           ${{ matrix.platform || matrix.target }} \
           ${{ matrix.output-format }} \
           --test --no-input --log -- --api-key=${{ secrets.API_KEY }}\
           ${{ matrix.briefcase-args }} \
           ${{ matrix.briefcase-run-args }}

     - name: Package App
       working-directory: ./pypass
       run: |
         ${{ matrix.briefcase-package-prefix }} \
         briefcase package \
           ${{ matrix.platform || matrix.target }} \
           ${{ matrix.output-format }} \
           --update --adhoc-sign --no-input --log \
           ${{ matrix.briefcase-args }} \
           ${{ matrix.briefcase-package-args }}

     - name: Upload App
       uses: actions/upload-artifact@v4
       with:
         name: App-${{ matrix.target }}
         path: pypass/dist
         if-no-files-found: error

     - name: Upload Log

       if: failure()
       uses: actions/upload-artifact@v4
       with:
         name: Log-Failure-${{ matrix.target }}
         path: pypass/logs/*
